### ISSUE TITLE
Adicionar ao gerador de ID o usuário do Windows

### ISSUE THREAD

**Issue by clvechini** [mobius1qwe/Aegys-Acesso-Remoto#36]
Adicionar o usuário do Windows na chave de criação do ID, hoje está sendo usado o macaddress e o número serial do HD, quando o Aegys Cliente é utilizado em Cliente de Terminal Service o número do ID está se repetindo.

**Comment by mobius1qwe** [comment]
Fixed on commit [76](https://github.com/mobius1qwe/Aegys-Acesso-Remoto/commit/f93600a27d38fdc9cd33fd97d57e299a2d2df1c4)
